name: Hugo Build and Deploy

permissions:
  pull-requests: write
  issues: write
  repository-projects: write

on:
  push:
    branches:
      - master  # Adjust this according to your main branch name

jobs:
  build:
    name: Build Site
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'  # You can specify a specific Hugo version if needed

    - name: Build
      run: hugo

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GH_PAGES_TOKEN }}
        publish_branch: master
        keep_files: true